services:
  - type: web
    name: apt-break-backend
    env: python
    buildCommand: cd apt-break/backend && pip install -r requirements.txt
    startCommand: cd apt-break/backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: FRONTEND_HOST
        value: https://aptbreak.com
      - key: API_V1_STR
        value: /api/v1
      - key: BACKEND_CORS_ORIGINS
        value: https://aptbreak.com
      - key: GOOGLE_REDIRECT_URI
        value: https://api.aptbreak.com/api/v1/auth/login/google/callback
      - key: PYTHON_VERSION
        value: 3.12.0

  - type: web
    name: apt-break-frontend
    env: node
    buildCommand: cd apt-break/frontend && npm install && npm run build
    startCommand: cd apt-break/frontend && npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://api.aptbreak.com
      - key: NODE_VERSION
        value: "20"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
        force: true
    healthCheckPath: / 